### ISSUE TITLE
JellyCon playback fails when using reverse proxy

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellycon#283]
**Describe the bug**
This issue has been bugging me for a long time but I finally figured out what's causing it. When using JellyCon and connecting to a server behind a nginx reverse proxy with ssl enabled (letsencrypt), playback either doesn't start at all, or stalls after 1-3 seconds and won't continue. Problem goes away if you bypass the proxy. Strangely, playback also works fine if you long-press and choose Force Transcode instead of playing normally. No other apps have problems with playback using the proxy (jellyfin-kodi, Webplayer, android-tv, Infuse, JMP, etc.)

**To Reproduce**
1. Use JellyCon with a server behind ssl enabled reverse proxy
2. Play a movie normally (just click on an item)
3. Playback stalls after a second or doesn't start at all

**Expected behavior**
Item plays normally.

**Logs**
No errors are logged.

**System (please complete the following information):**
 - OS: Android 11
 - Jellyfin Version: 10.8.10
 - Kodi Version: 20.1
 - Addon Version: 0.7.0

**Comment by SethFalco** [comment]
I have a very similar setup to you, but don't have this problem. Jellyfin, running on a server behind an NGINX proxy with Let's Encrypt.

Could it be related to either your Jellyfin setup, NGINX configuration, or firewall? Maybe just some things to double-check.

**Jellyfin**

Make sure in Jellyfin you have `PublishedServerUrl` set correctly. For example, if using Docker Compose, it'd look something like this:

```yml
version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:unstable
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
      - "1900:1900/udp"
      - "7359:7359/udp"
    user: 1000:1000
    restart: "unless-stopped"
    volumes:
      - ./config/:/config/
      - ./cache/:/cache/
      - ./media/:/media/ 
    environment:
      JELLYFIN_PublishedServerUrl: "https://jellyfin.example.org"
```

### NGINX

The Jellyfin documentation includes an in-depth NGINX configuration to use, if you haven't already, do give it a peek!

Reference: [Jellyfin Documentation for NGINX Reverse Proxy](https://jellyfin.org/docs/general/networking/nginx)

At a minimum, something like this should work which is what I use:

```
server {
  server_name jellyfin.example.org;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://localhost:8096/;
  }

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  # {{SSL stuff managed by Certbot}}
}

server {
  # {{SSL stuff managed by Certbot}}

  listen 80;
  listen [::]:80;

  server_name jellyfin.example.org;
  # {{SSL stuff managed by Certbot}}
}
```
